# Generated by Django 3.0.3 on 2020-02-22 18:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Task', '0001_initial'),
        ('Option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('title', models.CharField(max_length=25)),
                ('money', models.IntegerField()),
                ('start', models.TimeField()),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Option.Option')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.Task')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
