# Generated by Django 3.0.3 on 2020-02-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_remove_group_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.Group')),
            ],
        ),
    ]
