# Generated by Django 3.0.3 on 2020-02-23 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 18, 7, 56, 66560))),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.Task')),
            ],
        ),
    ]
