# Generated by Django 3.0.3 on 2020-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Completed_task', '0002_auto_20200223_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_task',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
