# Generated by Django 3.0.3 on 2020-02-23 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finisher',
            name='finished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 19, 8, 10, 192044)),
        ),
    ]
