# Generated by Django 3.0.3 on 2020-02-22 19:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('task_n', models.IntegerField(default=0)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.Group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
