# Generated by Django 2.2 on 2020-02-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Group.Group'),
        ),
    ]
